name: Build and publish
on:
# Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
    build:
        name: Build for ubuntu-latest
        runs-on: ubuntu-latest
        steps:
# checkout is nessesary
          - uses: actions/checkout@v2
#adding ssh key  https://maxschmitt.me/posts/github-actions-ssh-key/
          - name: Add SSH key
            env:
                SSH_AUTH_SOCK: /tmp/ssh_agent.sock
            run: |
                mkdir -p /home/runner/.ssh
                # Replace example.com with the hostname of the machine
                # you're SSH-ing into
                ssh-keyscan 178.176.224.186 >> /home/runner/.ssh/known_hosts
                # DOKKU_SSH_KEY is the name of the repository secret
                echo "${{ secrets.DOKKU_SSH_KEY }}" > /home/runner/.ssh/github_actions
                chmod 600 /home/runner/.ssh/github_actions
                ssh-agent -a $SSH_AUTH_SOCK > /dev/null 
                ssh-add /home/runner/.ssh/github_actions
# pushing directly to dokku
          - name: Setup SSH Keys and known_hosts
            env:
                SSH_AUTH_SOCK: /tmp/ssh_agent_github.sock
            run: |
                mkdir -p ~/.ssh
                ssh-keyscan github.com >> ~/.ssh/known_hosts
                ssh-agent -a $SSH_AUTH_SOCK > /dev/null
                ssh-add - <<< "${{ secrets.DOKKU_SSH_KEY }}"
          - name: git-remote-add and push
            env:
                SSH_AUTH_SOCK: /tmp/ssh_agent_github.sock
                BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
            run: |
                # git config --global user.email "actions@github.com"
                # git config --global user.name "GitHub actions" 
                git remote add dokku dokku@178.176.224.186:bot
                ssh root@178.176.224.186 "dokku config:set bot BOT_TOKEN=${{ secrets.BOT_TOKEN }}"
                git fetch --unshallow origin
                # ssh root@178.176.224.186 "dokku git:initialize bot"
                git push -u dokku main:main
